/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

;

/**
 *
 * @author Azael_Mendoza
 */
public class ViewBlocNotas extends javax.swing.JPanel {

    /**
     * Creates new form ViewBlocNotas
     */
    public ViewBlocNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_encabezado = new javax.swing.JLabel();
        jsp_area_trabajo = new javax.swing.JScrollPane();
        jta_area_trabajo = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 51, 51));

        jlb_encabezado.setFont(new java.awt.Font("PakType Naskh Basic", 1, 18)); // NOI18N
        jlb_encabezado.setForeground(new java.awt.Color(204, 204, 204));
        jlb_encabezado.setText("Bloc de Notas:");

        jta_area_trabajo.setBackground(new java.awt.Color(51, 51, 51));
        jta_area_trabajo.setColumns(20);
        jta_area_trabajo.setForeground(new java.awt.Color(204, 204, 204));
        jta_area_trabajo.setRows(5);
        jsp_area_trabajo.setViewportView(jta_area_trabajo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp_area_trabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_encabezado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_encabezado)
                .addGap(18, 18, 18)
                .addComponent(jsp_area_trabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jlb_encabezado;
    public javax.swing.JScrollPane jsp_area_trabajo;
    public javax.swing.JTextArea jta_area_trabajo;
    // End of variables declaration//GEN-END:variables
}
